/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Supervisor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.AppointmentDirectory;
import Business.Hospital.DoctorDirectory;
import Business.Hospital.VitalSignsDirectoryy;
import Business.Network.Network;
import Business.Organization.SupervisorOrganization;
import Business.Organization.TeamLeaderOrganization;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Recommendations.RecommendationDirectory;
import Business.Routine.FoodConsumptionTrackerDirectory;
import Business.Routine.SleepDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.WorkPlace.HolidayList;
import Business.WorkPlace.LeaveRequestHistory;
import Business.WorkPlace.Message;
import Business.WorkPlace.MyVaccationHistory;
import Business.WorkPlace.Supervisor;
import Business.WorkPlace.SupervisorDirectory;
import Business.WorkPlace.TeamLeader;
import Business.WorkPlace.TeamLeaderDirectory;
import Business.WorkPlace.WorkProgress;
import Business.WorkPlace.WorkProgressHistory;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nehah
 */
public class TeamLeaderWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form TeamLeaderWorkArea
     */
        JPanel userProcessContainer;
        Person p;
        DoctorDirectory	doctorList;
        UserAccountDirectory	uad;
        PersonDirectory	personList;
        SupervisorDirectory	supervisorList;
        MyVaccationHistory	leaveList;
        HolidayList	holidayList;
       // VaccationHelper1	vaccationHelper;
        AppointmentDirectory	appointmentDirectory;
        SleepDirectory	sleepDirectory;
        FoodConsumptionTrackerDirectory	foodTracker;
        VitalSignsDirectoryy	vitalSignList;
         LeaveRequestHistory leaveRequestDirectory;
         RecommendationDirectory recommmendationDirectory;
         WorkProgressHistory workProgress;
         TeamLeader t;
         UserAccount userAccount;
         TeamLeaderOrganization teamLeaderOrganization;
         Enterprise inEnterprise;
         EcoSystem system;
         Network n;
         TeamLeaderDirectory teamLeaderList;
    public TeamLeaderWorkArea(JPanel userProcessContainer, UserAccount userAccount, TeamLeaderOrganization teamLeaderOrganization, Enterprise inEnterprise, EcoSystem system, Network n) {
        
      initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.teamLeaderOrganization=teamLeaderOrganization;
        this.n=n;
        this.system=system;
        this.inEnterprise=inEnterprise;  
        this.teamLeaderList=teamLeaderOrganization.getTeamLeaderDirectory();
        t=teamLeaderList.findTeamLeaderByUserName(userAccount.getUsername());
        MessageTable();
        LoadPersonCombo();
        Person p=(Person)personCombo.getSelectedItem();
        populateTable(p);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        personCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        percentWorkProgressTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();
        dateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Team Leader Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        personCombo.setForeground(new java.awt.Color(255, 255, 255));
        personCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personComboActionPerformed(evt);
            }
        });
        add(personCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 270, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Person Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 220, -1));
        add(percentWorkProgressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 270, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Progress in percentage");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person", "Progress", "Supervisor", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 750, 140));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Requested Progress Report");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Send Progress to Supervisor>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 380, -1));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 270, -1));

        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message"
            }
        ));
        jScrollPane2.setViewportView(tblMessages);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 750, 100));
        add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 270, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void LoadPersonCombo(){
        personCombo.removeAll();
        for(Person per:t.getPersonList()){
            personCombo.addItem(per);
            
        }
    }
    public void MessageTable(){
        DefaultTableModel dtm =(DefaultTableModel)tblMessages.getModel();
        dtm.setRowCount(0);
        for (Message m:t.getMsgList())
            
        {
            Object row[]= new Object [1];
            row[0]=m.getMessage();
            dtm.addRow(row);
        }
    }
    public void populateTable(Person p){
        DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for (WorkProgress wp:p.getMyWorkProgress())
        //for(int i=0;i<(getBestStartDates.size());i++)    
        {
            Object row[]= new Object [4];
            row[0]=p.toString();
            row[1]=wp.getProgress();
            row[2]=wp.getSupervisor().getSupervisorName();
            row[3]=wp.getDate();
            dtm.addRow(row);
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(
                Integer.parseInt(percentWorkProgressTxt.getText())<0
                || percentWorkProgressTxt.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please select or enter valid values");
        }
        else{
        Person p=(Person)(personCombo.getSelectedItem());
        Supervisor s=p.getMySupervisor();
        Date date=dateChooser.getDate();
        WorkProgress wp=teamLeaderOrganization.getProgressHistory().addWorkProgress();
        wp.setP(p);
        wp.setSupervisor(s);
        wp.setDate(date);
        wp.setProgress(Integer.parseInt(percentWorkProgressTxt.getText()));
        p.getMyWorkProgress().add(wp);
        JOptionPane.showMessageDialog(null, "Progress added successfully.");
        //s.getProgressReport().add(wp);
        populateTable(p);
        
        }
                
    }//GEN-LAST:event_btnSaveActionPerformed

    private void personComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personComboActionPerformed
        // TODO add your handling code here:
        Person p=(Person)personCombo.getSelectedItem();
        populateTable(p);
    }//GEN-LAST:event_personComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
        
        else{
            Person p=(Person)personCombo.getSelectedItem();
            Supervisor s=p.getMySupervisor();
            WorkProgress wp=teamLeaderOrganization.getProgressHistory().findWorkProgressbyDateAndPerson((Date)jTable1.getValueAt(selectedRow, 3), p);
            s.getProgressReport().add(wp);
            //s.getProgressReport().
            JOptionPane.showMessageDialog(null, "Progress sent to Supervisor");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField percentWorkProgressTxt;
    private javax.swing.JComboBox personCombo;
    private javax.swing.JTable tblMessages;
    // End of variables declaration//GEN-END:variables
}
